In [1]:
import pandas as pd
#groupby 
#merge
#append
#concate
#join

In [2]:
df=pd.read_csv(r"C:\Users\hp\Desktop\IPL Matches 2008-2020.csv")
df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [6]:
a=[1,2,3]
b=[4,5,6]
c=a+b
c

[1, 2, 3, 4, 5, 6]

In [7]:
c.append(7)
c

[1, 2, 3, 4, 5, 6, 7]

In [11]:
df["city"].append(pd.Series("XYZ"))
#here we need to create series type data to append  xyz

C:\Users\hp\AppData\Local\Temp\ipykernel_2788\1282951080.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df["city"].append(pd.Series("XYZ"))

0       Bangalore
1      Chandigarh
2           Delhi
3          Mumbai
4         Kolkata
          ...
812         Dubai
813     Abu Dhabi
814     Abu Dhabi
815         Dubai
0             XYZ
Length: 817, dtype: object

In [15]:
#if we want to append data in multipal columns than we need to create data frame
#of city and venue than we need to create a data frame of new data to append to 
#another data frame of city and venue
df[["city","venue"]].append(pd.DataFrame(["xyz"]))

C:\Users\hp\AppData\Local\Temp\ipykernel_2788\3955178131.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df[["city","venue"]].append(pd.DataFrame(["xyz"]))

           city                                       venue    0
0     Bangalore                       M Chinnaswamy Stadium  NaN
1    Chandigarh  Punjab Cricket Association Stadium, Mohali  NaN
2         Delhi                            Feroz Shah Kotla  NaN
3        Mumbai                            Wankhede Stadium  NaN
4       Kolkata                                Eden Gardens  NaN
..          ...                                         ...  ...
812       Dubai         Dubai International Cricket Stadium  NaN
813   Abu Dhabi                        Sheikh Zayed Stadium  NaN
814   Abu Dhabi                        Sheikh Zayed Stadium  NaN
815       Dubai         Dubai International Cricket Stadium  NaN
0           NaN                                         NaN  xyz

[817 rows x 3 columns]